// apps/mynte.studio/inertia/components/hero.tsx
import { Cta } from '@mynte/design-system/cta'
import { MouseIcon } from '~/components/svg/mouse_icon'

export const Hero = () => {
  return (
    <section className="min-h-screen mx-5 flex flex-col items-center justify-around">
      <div className="flex flex-col items-center">
        <h1 className="text-principal font-semibold text-center max-w-[20ch] line-height-[120%]">
          <span className="font-serif italic mr-3 md:mr-5 font-normal mix-blend-difference">
            Refreshing
          </span>
          Digital experiences with creative design for every brand
        </h1>

        <p className="max-w-[50ch] text-center text-medium sm:text-lg md:text-xl lg:text-2xl mt-6">
          Websites, apps, e-commerce, graphic identities, graphic design, and advertising ; all
          crafted for a distinct digital presence
        </p>

        <div className="flex flex-col sm:flex-row justify-center gap-5 p-5 pt-10 text-center">
          <Cta as="a" href="https://blog.mynte.studio" variant="secondary">
            visit our blog
          </Cta>

          <Cta
            as="button"
            onClick={() => {
              Calendly.initPopupWidget({ url: 'https://calendly.com/admin-mynte/30min' })
              return false
            }}
          >
            book a call
          </Cta>
        </div>
      </div>

      <span className="flex gap-2 mb-4">
        <MouseIcon />
        Scroll down
      </span>
    </section>
  )
}

// inertia/components/hero/hero.vue
<script setup lang="ts">
import { useI18nExtended } from '~/composables/use_i18n_extended'
import Background from '~/components/hero/background.vue'
import TrustedBy from '../header/trusted_by.vue'

const { arabic, t } = useI18nExtended()
</script>

<template>
  <Background />
  <div class="min-h-[calc(100vh_-_6.25rem)] flex flex-col justify-between items-center">
    <div></div>
    <div class="flex flex-col items-center">
      <h1
        class="text-3xl sm:text-4xl md:text-5xl lg:text-7xl font-500 text-center max-w-[20ch] line-height-[120%]"
      >
        <span
          :class="[
            arabic ? 'font-ar-serif' : 'font-serif italic font-light',
            'mix-blend-difference',
          ]"
          >{{ t('keyword') }}</span
        >
        {{ t('title') }}
      </h1>

      <p class="max-w-[55ch] mx-auto mt-5 text-center text-lg md:text-2xl line-height-[120%]">
        {{ t('text') }}
      </p>
    </div>

    <TrustedBy />
  </div>
</template>

<i18n>
{
  "en": {
    "keyword": "Refreshing",
    "title": "Digital experiences with creative design for every brand",
    "text": "Websites, apps, e-commerce, graphic identities, graphic design, and advertising ; all crafted for a distinct digital presence"
  }
}
</i18n>
