// inertia/components/expertise/expertise.tsx
import { useState, useEffect, useRef, useMemo } from 'react'
import { SectionTitle } from '../section_title'
import { devTags, designTags, briefingTags, marketingTags } from './tags'
import { useLocomotiveScroll } from '../smooth_scroll_wrapper'

const expertiseData = [
  { title: 'Briefing, Research, & Conceptualization', tags: briefingTags },
  { title: 'Design', tags: designTags },
  { title: 'Development', tags: devTags },
  { title: 'Marketing', tags: marketingTags },
]

function shuffleTags(tags: string[]) {
  const shuffled = [...tags]
  // Fisher-Yates algorithm
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

export const Expertise = () => {
  const [activeIndex, setActiveIndex] = useState(0)
  const sectionRef = useRef<HTMLElement>(null)
  const { scroll } = useLocomotiveScroll()

  const shuffledTags = useMemo(() => {
    const allTags = [...briefingTags, ...designTags, ...devTags, ...marketingTags]
    return shuffleTags(allTags)
  }, [])

  useEffect(() => {
    if (!scroll) return

    const handleScroll = (args: any) => {
      if (!sectionRef.current) return

      const section = sectionRef.current
      const rect = section.getBoundingClientRect()
      const windowHeight = window.innerHeight
      const sectionHeight = section.offsetHeight

      const scrollStart = rect.top - windowHeight / 2
      const scrollEnd = rect.bottom - windowHeight / 2
      const scrollRange = sectionHeight - windowHeight / 2

      if (scrollStart > 0) {
        setActiveIndex(-1)
      } else if (scrollEnd < 0) {
        setActiveIndex(4)
      } else if (scrollEnd > 0 && scrollStart < 0) {
        const offset = windowHeight * 0.6
        const progress = Math.max(0, Math.min(1, (-scrollStart - offset) / scrollRange))
        const newIndex = Math.min(3, Math.floor(progress * 3.99))
        setActiveIndex(newIndex)
      }
    }

    scroll.on('scroll', handleScroll)

    return () => {
      scroll.off('scroll', handleScroll)
    }
  }, [scroll])

  const activeTags = activeIndex >= 0 && activeIndex <= 3 ? expertiseData[activeIndex].tags : []

  return (
    <section
      ref={sectionRef}
      id="expertise-section"
      className="mt-40 lg:min-h-[200vh] relative"
      data-scroll-section
    >
      {/* NOTE: mobile */}
      <div className="lg:hidden">
        <SectionTitle>our process and expertise</SectionTitle>

        <div className="mt-20 flex flex-col gap-10 items-start">
          {expertiseData.map((item, index) => (
            <div key={index} className="flex flex-col gap-4 items-start w-full">
              <h3 className="font-serif italic font-normal text-2xl text-left">{item.title}</h3>
              <div className="flex flex-wrap gap-3 justify-start">
                {item.tags.map((tag, tagIndex) => (
                  <h4
                    key={tagIndex}
                    className="glass flex justify-center items-center px-6 h-10 min-w-24 rounded-full"
                  >
                    {tag}
                  </h4>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* NOTE: desktop */}
      <div
        className="hidden lg:block relative top-[30vh]"
        data-scroll
        data-scroll-sticky
        data-scroll-target="#expertise-section"
      >
        <SectionTitle>our process and expertise</SectionTitle>

        <div className="mt-20 flex flex-nowrap">
          <aside className="w-1/2 flex flex-col gap-8">
            {expertiseData.map((item, index) => (
              <h3
                key={index}
                className={`font-serif font-normal italic transition-all duration-500 ease-out ${
                  activeIndex === -1 || activeIndex === 4
                    ? 'opacity-30 text-4xl'
                    : activeIndex === index
                      ? 'opacity-100 font-semibold text-4xl'
                      : 'opacity-40 text-4xl'
                }`}
                data-scroll
                data-scroll-speed={index * 0.5}
              >
                {item.title}
              </h3>
            ))}
          </aside>
          <div className="w-1/2 flex flex-wrap gap-5 justify-end">
            {shuffledTags.map((tag, index) => (
              <h4
                key={index}
                className={`glass flex justify-center items-center px-6 h-10 min-w-24 rounded-full transition-opacity duration-500 ease-out ${
                  activeIndex === -1 || activeIndex === 4
                    ? 'opacity-20'
                    : activeTags.includes(tag)
                      ? 'opacity-100'
                      : 'opacity-30'
                }`}
                data-scroll
                data-scroll-speed={0.2}
              >
                {tag}
              </h4>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}

// inertia/app/expertise/expertise.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, inject, computed, type Ref } from 'vue'
import type Lenis from 'lenis'
import { devTags, designTags, briefingTags, marketingTags } from './tags'

const expertiseData = [
  { title: 'Briefing, Research, & Conceptualization', tags: briefingTags },
  { title: 'Design', tags: designTags },
  { title: 'Development', tags: devTags },
  { title: 'Marketing', tags: marketingTags },
]

function shuffleTags(tags: string[]) {
  const shuffled = [...tags]
  // Fisher-Yates algorithm
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

const lenis = inject<Ref<Lenis | null>>('lenis')
const sectionRef = ref<HTMLElement | null>(null)
const activeIndex = ref(-1)
const shuffledTags = ref<string[]>([])

const activeTags = computed(() => {
  if (activeIndex.value >= 0 && activeIndex.value <= 3) {
    return expertiseData[activeIndex.value].tags
  }
  return []
})

const scrollHandler = () => {
  if (!sectionRef.value || !lenis?.value) return

  const rect = sectionRef.value.getBoundingClientRect()
  const viewportHeight = window.innerHeight
  const stickyOffset = viewportHeight * 0.25 // 25vh

  if (rect.top > stickyOffset) {
    activeIndex.value = -1
    return
  }

  const sectionHeight = rect.height

  // Distance totale scrollable une fois le sticky actif
  const scrollableDistance = sectionHeight - viewportHeight
  const scrolled = stickyOffset - rect.top
  const progress = Math.max(0, Math.min(1, scrolled / scrollableDistance))

  if (progress >= 1) {
    activeIndex.value = 4
  } else {
    const index = Math.min(3, Math.floor(progress * 4))
    activeIndex.value = index
  }
}

onMounted(() => {
  const allTags = [...briefingTags, ...designTags, ...devTags, ...marketingTags]
  shuffledTags.value = shuffleTags(allTags)

  // Attendre que Lenis soit initialisé
  const checkLenis = setInterval(() => {
    if (lenis?.value) {
      clearInterval(checkLenis)

      // Écouter l'événement scroll de Lenis
      lenis.value.on('scroll', scrollHandler)

      // Appeler une première fois pour initialiser
      scrollHandler()
    }
  }, 100)

  // Cleanup du setInterval après 5 secondes si Lenis n'est pas trouvé
  setTimeout(() => clearInterval(checkLenis), 5000)
})

onUnmounted(() => {
  if (lenis?.value) {
    lenis.value.off('scroll', scrollHandler)
  }
})

function getTitleClasses(index: number) {
  const baseClasses =
    'font-serif font-normal italic transition-all duration-500 ease-out max-w-[25ch]'

  if (activeIndex.value === -1 || activeIndex.value === 4) {
    return `${baseClasses} opacity-30 text-4xl`
  } else if (activeIndex.value === index) {
    return `${baseClasses} opacity-100 text-4xl`
  } else {
    return `${baseClasses} opacity-40 text-4xl`
  }
}

function getTagClasses(tag: string) {
  const baseClasses =
    'glass flex justify-center items-center px-6 h-10 min-w-24 transition-opacity duration-500 ease-out'

  if (activeIndex.value === -1 || activeIndex.value === 4) {
    return `${baseClasses} opacity-20`
  } else if (activeTags.value.includes(tag)) {
    return `${baseClasses} opacity-100`
  } else {
    return `${baseClasses} opacity-30`
  }
}
</script>

<template>
  <section ref="sectionRef" id="expertise-section" class="mt-40 xl:min-h-[200vh] relative pb-30">
    <!-- Mobile version -->
    <div class="xl:hidden">
      <h2>OUR PROCESS AND EXPERTISE</h2>

      <div class="mt-20 flex flex-col gap-10 items-start">
        <div
          v-for="(item, index) in expertiseData"
          :key="index"
          class="flex flex-col gap-4 items-start w-full"
        >
          <h3 class="font-serif italic font-normal text-2xl text-left">
            {{ item.title }}
          </h3>
          <div class="flex flex-wrap gap-3 justify-start">
            <h4
              v-for="(tag, tagIndex) in item.tags"
              :key="tagIndex"
              class="glass flex justify-center items-center px-6 h-10 min-w-24"
            >
              {{ tag }}
            </h4>
          </div>
        </div>
      </div>
    </div>

    <!-- Desktop version -->
    <div class="hidden xl:block sticky xl:top-[15vh] 2xl:top-[25vh] left-0 right-0">
      <h2>OUR PROCESS AND EXPERTISE</h2>

      <div class="mt-20 flex flex-nowrap">
        <aside class="w-1/2 flex flex-col gap-15">
          <h3 v-for="(item, index) in expertiseData" :key="index" :class="getTitleClasses(index)">
            {{ item.title }}
          </h3>
        </aside>
        <div class="w-1/2 flex flex-wrap gap-5 justify-end">
          <h4 v-for="(tag, index) in shuffledTags" :key="index" :class="getTagClasses(tag)">
            {{ tag }}
          </h4>
        </div>
      </div>
    </div>
  </section>
</template>
