// inertia/components/header/header.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3'
import Logo from '~/components/svg/logo.vue'
import DxbTime from './dxb_time.vue'
import Lang from './lang.vue'
import { useScrollDirection } from '~/composables/use_scroll_direction'

const { isScrollingDown } = useScrollDirection()
</script>

<template>
  <header
    dir="ltr"
    class="fixed top-0 left-0 right-0 z-50 transition-opacity duration-300"
    :class="{ 'opacity-0 pointer-events-none': isScrollingDown }"
    @click.stop
  >
    <div class="container mx-auto h-25 flex justify-between items-center px-5">
      <Link href="/"><Logo /></Link>

      <div class="flex gap-1">
        <DxbTime />
        <span>|</span>
        <Lang />
      </div>
    </div>
  </header>
</template>

// inertia/components/header/header.tsx
import { Link } from '@inertiajs/react'
import Cookies from 'js-cookie'
import { useTranslation } from '~/hooks/useTranslation'
import { Logo } from '~/components/svgs/logo'
import { tuyau } from '~/core/providers/tuyau'
import { DynamicIsland } from '~/components/header/dynamic_island'
import { DxbTime } from '~/components/header/dxb_time'
import { ExternalLinks } from '~/components/header/external_links'

export const Header = () => {
  const { i18n } = useTranslation()

  function handleChangeLanguage() {
    const newLang = i18n.language === 'ar' ? 'en' : 'ar'
    i18n.changeLanguage(newLang)
    Cookies.set('locale', newLang, { expires: 365 })
  }

  return (
    <header
      dir="ltr"
      className="container fixed top-0 left-0 right-0 mx-auto z-99 px-5 py-5 lg:py-9 grid grid-cols-2 md:grid-cols-4 items-center text-sm"
    >
      {/* NOTE: left */}
      <div className="col-start-1 col-end-2 lg:col-end-1">
        <Link href={tuyau.$url('home.render')}>
          <Logo />
        </Link>
      </div>

      {/* NOTE: center */}
      <div className="hidden lg:flex col-start-2 col-end-4">
        <DynamicIsland />
      </div>

      {/* NOTE: right */}
      <div className="col-start-4 flex gap-4 justify-end items-center font-en">
        <div className="flex gap-1">
          <div className="hidden sm:flex">
            <DxbTime />
          </div>
          <span className="flex gap-1">
            <span className="hidden sm:flex">|</span>
            <button
              onClick={handleChangeLanguage}
              className={i18n.language === 'ar' ? 'font-en' : 'font-ar italic'}
            >
              {i18n.language === 'ar' ? 'ENG' : 'عربي'}
            </button>
          </span>
        </div>
        <ExternalLinks />
      </div>
    </header>
  )
}
